version: "3.5"
services:

  # clinic-app:
  #   container_name: clinic-app
  #   build:
  #     context: ./nextjs
  #     # dockerfile: Dockerfile.prod # teste de produção
  #     dockerfile: Dockerfile.dev # teste em dev
  #   restart: always
  #   tty: true # comentar para teste de produção
  #   entrypoint: ["sh", "-c"] # comentar para teste de produção
  #   # command: ["npm install && npm run dev"] # comentar para teste de produção
  #   command: ["npm run dev"] # comentar para teste de produção
  #   environment:
  #     NEXTAUTH_URL: http://localhost:3001
  #     NEXTAUTH_SECRET: my-secret-goes-here-abc-123
  #     AUTH_ISSUER: http://host.docker.internal:8080/realms/clinic-manager
  #     KEYCLOAK_CLIENT_ID: next-clinic-manager
  #     KEYCLOAK_CLIENT_SECRET: 4BoZYrQWHFj5wu1ZyaxLRuhYUz8Yk5aU
  #     KEYCLOAK_LOGOUT_URL: http://host.docker.internal:8080/realms/clinic-manager/protocol/openid-connect/logout
  #     BACKEND_URL: http://host.docker.internal:3000
  #     FAKE_API_URL: http://localhost:8000
  #     KEYCLOAK_REFRESH_TOKEN_URL: http://localhost:8080/realms/clinic-manager/protocol/openid-connect/token
  #   ports:
  #     - 3001:3001 # app
  #     - 8000:8000 # fake API
  #   volumes:
  #     - ./nextjs/:/home/node/app
  #   extra_hosts:
  #     - host.docker.internal:172.17.0.1

  # clinic-api:
  #   # image: igorlage/painel-gestor-back:0.0.1 # producao
  #   build: # desenvolvimento
  #     context: ./nestjs
  #     # dockerfile: Dockerfile.prod # teste de produção
  #     dockerfile: Dockerfile.dev # teste em dev
  #   container_name: clinic-api
  #   restart: always
  #   tty: true # comentar para teste de produção
  #   entrypoint: ["sh", "-c"] # comentar para teste de produção
  #   # command: ["npm install && npm run start:dev"] # comentar para teste de produção
  #   command: ["npm run start:dev"] # comentar para teste de produção
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     API_PORT: 3000
  #     INSTANCE_HOST: clinic-db
  #     DB_PORT: 5432
  #     DB_NAME: pagamento
  #     DB_USER: pguser
  #     DB_PASS: pgpass
  #     ssynchronize: 1
  #     logging: 1
  #     # keycloak
  #     JWT_SECRET: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnujGPYyqJzabqQ6KZast7rH/HiVkMlHdw6IBE24pbVWeNwoSNoCcmDLbVDU/Hg7YNbH5Pn+5/sqFFfB800l2HctT6qNfQdhLXYUUJfKH+ytPV5pPyxwa5vSo6a1RZFdlRtUE9Ib1amaOmSzR6oUyWZJmfv4p4M/0N23D1A9FC0PT5cHBRAqJcgugrvRPnK7XpJX772MKAtJJbIATc9WhQJqUiwWQ2t9plpLQ3OdvncSY4cR8QQPdc8VLkmGln762wTCphjCd13M7Ou65EsX+U14dzBR9CwQYk9xGqkVfdb2hlwCdulqZS5iXllQyhYlfHczEyaKsGw904ft/BUJprwIDAQAB\n-----END PUBLIC KEY-----"
  #     KC_HOST: http://keycloak:8080
  #     KC_REALM: clinic-manager
  #     KC_CLIENT_ID: clinic-manager-api
  #     KC_CLIENT_SECRET: RtDauBV2SFeCTjcBNpEdU9lXwaRbM1xf
  #   volumes:
  #     - ./nestjs/:/home/node/app
  #   depends_on:
  #     - clinic-db

  # clinic-db:
  #   image: postgres:11
  #   container_name: clinic-db
  #   restart: always
  #   volumes:
  #     - ./db/back/postgres/data:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   healthcheck:
  #     test: exit 0
  #   environment:
  #     POSTGRES_USER: pguser
  #     POSTGRES_PASSWORD: pgpass
  #     POSTGRES_DB: pagamento

  # redis:
  #   container_name: redis
  #   image: redis:7.0.8-alpine
  #   restart: always

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    command: ["start-dev"]
    restart: always
    environment:
      # keycloak varables
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 123
      # database varables
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: pguser
      KC_DB_PASSWORD: 123
      KC_DB_SCHEMA: public
      KC_HEALTH_ENABLED: true
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      - keycloak-db

  keycloak-db:
    container_name: keycloak-db
    image: postgres:11
    restart: always
    volumes:
      - ./db/keycloak/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432
    healthcheck:
      test: exit 0
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: 123