###
GET http://localhost:3000

###
GET http://localhost:3000/plano

###
# @name createPlano
POST http://localhost:3000/plano
Content-Type: application/json

{
  "titulo": "Plano Básico",
  "descricao": "Descrição detalhada do plano básico",
  "preco": 199.99,
  "periodo_teste": 7,
  "max_matriz": 1,
  "max_filiais": 1,
  "colaboradores": 1,
  "convites": 0,
  "ativo": false,
  "validade": "2023-10-15T15:56:27.351Z"
}

###
@plano_id = {{createPlano.response.body.data.id}}

###
GET http://localhost:3000/plano/{{plano_id}}

###
PATCH  http://localhost:3000/plano/{{plano_id}}
Content-Type: application/json

{
  "ativo": true
}
